AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app
    Sample SAM Template for sam-app
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 100


Resources:

    LogSearchFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: target/scala-2.13/logsearch-service-assembly-0.1.jar
            Handler: LogSearcherService::handleRequest
            Runtime: java11
            # Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                # Variables:
                    # PARAM1: VALUE
            Events:
                RootEndPoint:
                    Type: Api
                    Properties:
                        Path: /
                        Method: any
                LogSearch:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /findLogs/{proxy+}
                        Method: any

Outputs:

    LogSearchAPI:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/findLogs/"

    LogSearchFunction:
      Description: "Log Search Lambda Function ARN"
      Value: !GetAtt LogSearchFunction.Arn

    LogSearchFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt LogSearchFunctionRole.Arn